version: "3.8"
services:
  consul:
    image: library/consul:${CONSUL_IMAGE_VERSION}
    # Run development mode of Consul
    command: "consul agent -dev -client 0.0.0.0"
    ports:
      - "8500:8500" # Consul UI
